#!/usr/bin/env bash
set -euo pipefail

REPO_DIR="${BUILDING_PRICE_INTEL_DIR:-/home/huanghonsen/building-price-intel}"
# Load .env for local defaults, but preserve explicit caller overrides from
# wrappers/cron invocations such as the national V4 runner.
_DAILY_CRAWL_KEYWORDS_SET="${DAILY_CRAWL_KEYWORDS+x}"; _DAILY_CRAWL_KEYWORDS_VALUE="${DAILY_CRAWL_KEYWORDS-}"
_DAILY_CRAWL_RETRY_ATTEMPTS_SET="${DAILY_CRAWL_RETRY_ATTEMPTS+x}"; _DAILY_CRAWL_RETRY_ATTEMPTS_VALUE="${DAILY_CRAWL_RETRY_ATTEMPTS-}"
_DAILY_CRAWL_RETRY_BACKOFF_SECONDS_SET="${DAILY_CRAWL_RETRY_BACKOFF_SECONDS+x}"; _DAILY_CRAWL_RETRY_BACKOFF_SECONDS_VALUE="${DAILY_CRAWL_RETRY_BACKOFF_SECONDS-}"
_DAILY_BRIEFING_REGIONS_SET="${DAILY_BRIEFING_REGIONS+x}"; _DAILY_BRIEFING_REGIONS_VALUE="${DAILY_BRIEFING_REGIONS-}"
_DAILY_BRIEFING_CATEGORIES_SET="${DAILY_BRIEFING_CATEGORIES+x}"; _DAILY_BRIEFING_CATEGORIES_VALUE="${DAILY_BRIEFING_CATEGORIES-}"
_BID_ALERT_KEYWORDS_SET="${BID_ALERT_KEYWORDS+x}"; _BID_ALERT_KEYWORDS_VALUE="${BID_ALERT_KEYWORDS-}"
_BID_ALERT_REGIONS_SET="${BID_ALERT_REGIONS+x}"; _BID_ALERT_REGIONS_VALUE="${BID_ALERT_REGIONS-}"
_WECOM_WEBHOOK_URL_SET="${WECOM_WEBHOOK_URL+x}"; _WECOM_WEBHOOK_URL_VALUE="${WECOM_WEBHOOK_URL-}"
if [ -f "$REPO_DIR/.env" ]; then
  set -a
  . "$REPO_DIR/.env"
  set +a
fi
[ -n "$_DAILY_CRAWL_KEYWORDS_SET" ] && DAILY_CRAWL_KEYWORDS="$_DAILY_CRAWL_KEYWORDS_VALUE"
[ -n "$_DAILY_CRAWL_RETRY_ATTEMPTS_SET" ] && DAILY_CRAWL_RETRY_ATTEMPTS="$_DAILY_CRAWL_RETRY_ATTEMPTS_VALUE"
[ -n "$_DAILY_CRAWL_RETRY_BACKOFF_SECONDS_SET" ] && DAILY_CRAWL_RETRY_BACKOFF_SECONDS="$_DAILY_CRAWL_RETRY_BACKOFF_SECONDS_VALUE"
[ -n "$_DAILY_BRIEFING_REGIONS_SET" ] && DAILY_BRIEFING_REGIONS="$_DAILY_BRIEFING_REGIONS_VALUE"
[ -n "$_DAILY_BRIEFING_CATEGORIES_SET" ] && DAILY_BRIEFING_CATEGORIES="$_DAILY_BRIEFING_CATEGORIES_VALUE"
[ -n "$_BID_ALERT_KEYWORDS_SET" ] && BID_ALERT_KEYWORDS="$_BID_ALERT_KEYWORDS_VALUE"
[ -n "$_BID_ALERT_REGIONS_SET" ] && BID_ALERT_REGIONS="$_BID_ALERT_REGIONS_VALUE"
[ -n "$_WECOM_WEBHOOK_URL_SET" ] && WECOM_WEBHOOK_URL="$_WECOM_WEBHOOK_URL_VALUE"
PYTHON_BIN="${BUILDING_PRICE_INTEL_PYTHON:-/home/huanghonsen/projects/construction-price-app/building-price-intel/.venv/bin/python}"
DB_PATH="${BUILDING_PRICE_INTEL_DB:-$REPO_DIR/local_prod.db}"
export DATABASE_URL="${DATABASE_URL:-sqlite+pysqlite:///$DB_PATH}"
export DAILY_CRAWL_KEYWORDS="${DAILY_CRAWL_KEYWORDS:-脚手架,盘扣脚手架,钢材,废钢}"
export DAILY_BRIEFING_REGIONS="${DAILY_BRIEFING_REGIONS:-广东,华北,内蒙古}"
export DAILY_BRIEFING_CATEGORIES="${DAILY_BRIEFING_CATEGORIES:-steel,scrap,scaffold}"
export BID_ALERT_KEYWORDS="${BID_ALERT_KEYWORDS:-脚手架,盘扣,租赁,钢管}"
export BID_ALERT_REGIONS="${BID_ALERT_REGIONS:-广东,广州,深圳,佛山,内蒙古,华北}"
export BID_ALERT_MIN_AMOUNT="${BID_ALERT_MIN_AMOUNT:-1000000}"

cd "$REPO_DIR"
mkdir -p "$(dirname "$DB_PATH")" app/crawlers/logs

alembic upgrade head
if [ "${BOOTSTRAP_SEED_IF_EMPTY:-1}" = "1" ]; then
  PRICE_COUNT=$("$PYTHON_BIN" - <<'PY'
from sqlalchemy import select, func
from app.core.database import SessionLocal
from app.models.price import PriceDaily
with SessionLocal() as db:
    print(db.scalar(select(func.count()).select_from(PriceDaily)) or 0)
PY
)
  if [ "$PRICE_COUNT" = "0" ]; then
    "$PYTHON_BIN" -m app.seed.seed_data
  fi
fi
"$PYTHON_BIN" scripts/daily_ops_pipeline.py "$@"
